name: Create Simple Node App

on:
  workflow_dispatch:

jobs:
  create-node-app:
    runs-on: ubuntu-latest

    permissions:
      contents : write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Node.js app files
        run: |
          mkdir -p my-node-app

          # Create package.json
          cat <<EOF > my-node-app/package.json
          {
            "name": "my-node-app",
            "version": "1.0.0",
            "description": "Simple Node.js app",
            "main": "app.js",
            "scripts": {
              "start": "node app.js"
            },
            "author": "",
            "license": "ISC"
          }
          EOF

          # Create app.js
          cat <<EOF > my-node-app/app.js
          const http = require('http');
          const hostname = '127.0.0.1';
          const port = 3000;
          const server = http.createServer((req, res) => {
            res.statusCode = 200;
            res.setHeader('Content-Type', 'text/plain');
            res.end('Hello, World!\\n');
          });
          server.listen(port, hostname, () => {
            console.log(\`Server running at http://\${hostname}:\${port}/\`);
          });
          EOF

      - name: Run npm install
        run: |
          npm install --prefix my-node-app

      - name: Commit and push files
        run: |
          git add my-node-app/
          git commit -m "Add simple Node.js app via GitHub Actions" || echo "Nothing to commit"
          git push
